import { logger } from "../lib/logger";
import fs from "fs";
import path from "path";
import os from "os";
import zlib from "zlib";
import { promisify } from "util";

const gzip = promisify(zlib.gzip);
const gunzip = promisify(zlib.gunzip);

const SESSION_PREFIX = "NUTTERXMD";

export type SessionFileMap = Record<string, unknown>;

export async function loadSessionFromEnv(): Promise<{
  state: { creds: unknown; keys: unknown };
  saveCreds: () => Promise<void>;
} | null> {
  const sessionId = process.env["SESSION_ID"];
  if (!sessionId) {
    logger.info("No SESSION_ID env var found — bot will not start");
    return null;
  }

  // Validate that this SESSION_ID belongs to NUTTER-XMD
  if (!sessionId.startsWith(SESSION_PREFIX)) {
    logger.error(
      { prefix: sessionId.slice(0, 12) },
      `Invalid SESSION_ID: must start with "${SESSION_PREFIX}". This session was not generated by NUTTER-XMD.`
    );
    return null;
  }

  const encoded = sessionId.slice(SESSION_PREFIX.length);

  try {
    const raw = Buffer.from(encoded, "base64");

    let jsonStr: string;
    // Gzip magic bytes: 0x1f 0x8b
    if (raw[0] === 0x1f && raw[1] === 0x8b) {
      const decompressed = await gunzip(raw);
      jsonStr = decompressed.toString("utf-8");
    } else {
      // Legacy uncompressed session ID (no prefix, backward compat)
      jsonStr = raw.toString("utf-8");
    }

    const fileMap = JSON.parse(jsonStr) as SessionFileMap;

    const { useMultiFileAuthState } = await import("@whiskeysockets/baileys");

    const sessionDir = path.join(os.tmpdir(), `nutter-xmd-session-${process.pid}`);
    if (fs.existsSync(sessionDir)) {
      fs.rmSync(sessionDir, { recursive: true, force: true });
    }
    fs.mkdirSync(sessionDir, { recursive: true });

    for (const [filename, content] of Object.entries(fileMap)) {
      fs.writeFileSync(path.join(sessionDir, filename), JSON.stringify(content), "utf-8");
    }

    const authState = await useMultiFileAuthState(sessionDir);
    logger.info({ sessionDir }, "Session loaded from SESSION_ID env var");
    return authState;
  } catch (err) {
    logger.error({ err }, "Failed to parse SESSION_ID — ensure it is a valid NUTTER-XMD session string");
    return null;
  }
}

export async function encodeSessionToBase64(fileMap: SessionFileMap): Promise<string> {
  // Only creds.json is needed to re-authenticate. All Signal protocol state
  // files (pre-keys, sessions, sender-keys) are rebuilt automatically by
  // Baileys as the bot interacts with WhatsApp. Storing only creds.json
  // keeps the SESSION_ID tiny enough to fit in Heroku's 64 kB config var limit.
  const essential: SessionFileMap = {};
  if (fileMap["creds.json"] !== undefined) {
    essential["creds.json"] = fileMap["creds.json"];
  } else {
    // Fallback: include everything if creds.json isn't found by that name
    Object.assign(essential, fileMap);
  }
  const json = Buffer.from(JSON.stringify(essential), "utf-8");
  const compressed = await gzip(json);
  // Prefix with NUTTERXMD so the bot engine can verify the session origin
  return SESSION_PREFIX + compressed.toString("base64");
}
